### PR TITLE
Master

### PR DESCRIPTION
**Pull request by JoseConseco**
Hi, great job on including linear gradient, and random colors. 
I just modified some stuff, becaouse it didn't work on blender 2.79a.
Also I  reworked masking - instead of using custom property, now VCM is using build in blender buttons for masking. I think this is more convenient this way.
List of changes:
- use blender build-in vertex/face mask buttons (blender 2.79 doesn't support vert masking, but 2.79a will have it - should be out soon)
- compabilitity with blender 2.79a (eg. blender 2.79a won't support Color(x,y,z,c) - 4 params, it will stay 3 len - I asked core blender devs about it, so I used app.version instead)
- linear gradient - support for vert mask, and face mask,
- random color - remove 'selection only' - use face, vert mask instead. Add seeed, revorked coloring a bit.

### CODE REVIEW

**Comment by JoseConseco** [comment]
Also I saw you implemented linear  gradient custom colors, but thing is, it won't work with modal operator (after pressing f6, user won't be able to change colors). I do not think there is way around it (unless maybe using foreground, and background color from paint colors...)

**Comment by JoseConseco** [comment]
"What is the reason for needing a seed for the random colours?"
For example see  difference - ordered (left) vs random(rigth) islands color :
image
Both have their uses.
Seed - as you mentioned, It helps you get same result on new execution of operator (useful if you already masked ID colors in texture software, but you have to remake mesh slightly and bake ID's again).
BTW.  I'm thinking - maybe actually ordered vert color, also need some offset value - to get different colors if users want - but I guess it can be done with HSV sliders now...

Also - not sure why - but randomizing hue dosen't work right now. I get always red results when using random mehs island  colors. I may check this out later...

**Comment by JoseConseco** [comment]
Ok. Found out why hue randomization won't work. In line  872:
is:
color = Color((1, 1, 1))
but should be:
color = Color((1, 0, 0))
You can't change hue on white color, that is why it didn't work.

**Comment by andyp123** [comment]
Doh! I was changed that bit of code to make the flow easier to read and then introduced a bug. Thanks for pointing it out. It's fixed now. I also added the HSV offset to random island colors, which was something I was going to add before but didn't get around to.

**Pull request merged**
